### ISSUE TITLE
dmc_unrar_extract_file_with_callback declared, but not implemented

### ISSUE THREAD

**Issue by fasterthanlime** [DrMcCoy/dmc_unrar#1]
I see the forward declaration here:

https://github.com/DrMcCoy/dmc_unrar/blob/c414853a3c6cfc3b4bab963a794773e5116e6f6e/dmc_unrar.c#L688-L709

but no actual implementation!

Looking at `dmc_unrar_extract_file_to_mem`, it shouldn't be too hard to implement though:

https://github.com/DrMcCoy/dmc_unrar/blob/c414853a3c6cfc3b4bab963a794773e5116e6f6e/dmc_unrar.c#L3622-L3663

so I might just give it a shot.

**Comment by DrMcCoy** [comment]
Huh. I might have forgotten to implement that, then. Which is weird, because I thought I tested that. O_o

Maybe it got lost in a rebase, or I forgot to commit that bit when I did a git add -p and then clobbered it. Not the first time that happened to me.

**Comment by DrMcCoy** [comment]
So yeah, thanks for giving dmc_unrar a spin, and finding all my embarassing mistakes for me! :D

**Comment by DrMcCoy** [comment]
Fixed with #2 in 9c4b746b7e5e3031934403f6f633fde9e1c4a7cd.
